//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_Persona
    {
        public string turno { get; set; }
        public long persona_id { get; set; }
        public long area_id { get; set; }
        public long fecha_id { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Fecha Fecha { get; set; }
    }
}
