//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area_Categoria
    {
        public long mañana { get; set; }
        public long tarde { get; set; }
        public long noche { get; set; }
        public long categoria_id { get; set; }
        public long area_id { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
