//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asueto
    {
        public long id { get; set; }
        public string fechaInicio { get; set; }
        public string fechaFin { get; set; }
        public string tipo { get; set; }
        public long persona_id { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
